package gob.bcb.bpm.pruebaCU;

// Generated 16-08-2011 03:21:05 PM by Hibernate Tools 3.4.0.CR1

import gob.bcb.core.infra.datastore.BcbEntity;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura extends BcbEntity  {

  private FacturaId id;
  private char cveRegistroRuc;
  private String ruc;
  private String nombre;
  private String nroOrden;
  private String nroFactura;
  private String codFactura;
  private Date fechaFactura;
  private BigDecimal montoFactura;
  private BigDecimal montoIce;
  private char cveEstadoFactura;
  private String codUsuario;
  private Date fechaHora;
  private String estacion;
  private char cveCrDb;
  private BigDecimal montoIva;

  public Factura() {
  }

  public Factura(FacturaId id, char cveRegistroRuc, Date fechaFactura,
      BigDecimal montoFactura, BigDecimal montoIce, char cveEstadoFactura,
      String codUsuario, Date fechaHora, char cveCrDb, BigDecimal montoIva) {
    this.id = id;
    this.cveRegistroRuc = cveRegistroRuc;
    this.fechaFactura = fechaFactura;
    this.montoFactura = montoFactura;
    this.montoIce = montoIce;
    this.cveEstadoFactura = cveEstadoFactura;
    this.codUsuario = codUsuario;
    this.fechaHora = fechaHora;
    this.cveCrDb = cveCrDb;
    this.montoIva = montoIva;
  }

  public Factura(FacturaId id, char cveRegistroRuc, String ruc, String nombre,
      String nroOrden, String codFactura, Date fechaFactura,
      BigDecimal montoFactura, BigDecimal montoIce, char cveEstadoFactura,
      String codUsuario, Date fechaHora, String estacion, char cveCrDb,
      BigDecimal montoIva) {
    this.id = id;
    this.cveRegistroRuc = cveRegistroRuc;
    this.ruc = ruc;
    this.nombre = nombre;
    this.nroOrden = nroOrden;
    this.codFactura = codFactura;
    this.fechaFactura = fechaFactura;
    this.montoFactura = montoFactura;
    this.montoIce = montoIce;
    this.cveEstadoFactura = cveEstadoFactura;
    this.codUsuario = codUsuario;
    this.fechaHora = fechaHora;
    this.estacion = estacion;
    this.cveCrDb = cveCrDb;
    this.montoIva = montoIva;
  }
  
  public Factura(FacturaId id, char cveRegistroRuc, String ruc, String nombre,
      String nroOrden, String nroFactura, String codFactura, Date fechaFactura,
      BigDecimal montoFactura, BigDecimal montoIce, char cveEstadoFactura,
      String codUsuario, Date fechaHora, String estacion, char cveCrDb,
      BigDecimal montoIva) {
    this.id = id;
    this.cveRegistroRuc = cveRegistroRuc;
    this.ruc = ruc;
    this.nombre = nombre;
    this.nroOrden = nroOrden;
    this.nroFactura = nroFactura;
    this.codFactura = codFactura;
    this.fechaFactura = fechaFactura;
    this.montoFactura = montoFactura;
    this.montoIce = montoIce;
    this.cveEstadoFactura = cveEstadoFactura;
    this.codUsuario = codUsuario;
    this.fechaHora = fechaHora;
    this.estacion = estacion;
    this.cveCrDb = cveCrDb;
    this.montoIva = montoIva;
  }

  public FacturaId getId() {
    return this.id;
  }

  public void setId(FacturaId id) {
    this.id = id;
  }

  public char getCveRegistroRuc() {
    return this.cveRegistroRuc;
  }

  public void setCveRegistroRuc(char cveRegistroRuc) {
    this.cveRegistroRuc = cveRegistroRuc;
  }

  public String getRuc() {
    return this.ruc;
  }

  public void setRuc(String ruc) {
    this.ruc = ruc;
  }

  public String getNombre() {
    return this.nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public String getNroOrden() {
    return this.nroOrden;
  }

  public void setNroOrden(String nroOrden) {
    this.nroOrden = nroOrden;
  }

  public String getNroFactura() {
    return this.nroFactura;
  }

  public void setNroFactura(String nroFactura) {
    this.nroFactura = nroFactura;
  }

  public String getCodFactura() {
    return this.codFactura;
  }

  public void setCodFactura(String codFactura) {
    this.codFactura = codFactura;
  }

  public Date getFechaFactura() {
    return this.fechaFactura;
  }

  public void setFechaFactura(Date fechaFactura) {
    this.fechaFactura = fechaFactura;
  }

  public BigDecimal getMontoFactura() {
    return this.montoFactura;
  }

  public void setMontoFactura(BigDecimal montoFactura) {
    this.montoFactura = montoFactura;
  }

  public BigDecimal getMontoIce() {
    return this.montoIce;
  }

  public void setMontoIce(BigDecimal montoIce) {
    this.montoIce = montoIce;
  }

  public char getCveEstadoFactura() {
    return this.cveEstadoFactura;
  }

  public void setCveEstadoFactura(char cveEstadoFactura) {
    this.cveEstadoFactura = cveEstadoFactura;
  }

  public String getCodUsuario() {
    return this.codUsuario;
  }

  public void setCodUsuario(String codUsuario) {
    this.codUsuario = codUsuario;
  }

  public Date getFechaHora() {
    return this.fechaHora;
  }

  public void setFechaHora(Date fechaHora) {
    this.fechaHora = fechaHora;
  }

  public String getEstacion() {
    return this.estacion;
  }

  public void setEstacion(String estacion) {
    this.estacion = estacion;
  }

  public char getCveCrDb() {
    return this.cveCrDb;
  }

  public void setCveCrDb(char cveCrDb) {
    this.cveCrDb = cveCrDb;
  }

  public BigDecimal getMontoIva() {
    return this.montoIva;
  }

  public void setMontoIva(BigDecimal montoIva) {
    this.montoIva = montoIva;
  }

}
